dbt-template-profile:
  outputs:
    dev:
      dataset: dbt_template
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: playground-447116
      threads: 1
      type: bigquery
  target: dev
